name: Build kernel with commit and create .deb files

on:
  push:
    branches:
      - test-commit

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install necessary  package
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential fakeroot bc python3 bison flex libelf-dev libssl-dev libncurses-dev dwarves lz4 devscripts dkms vim make wget

      - name: Get kernel source from commit
        run: |
          sudo apt-get install -y git
          git clone https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy
          cd jammy/
          git checkout 28529530a96faaebe46d311636d45fdc9b9de164
          make ARCH=i386 defconfig
          sed -i 's/CONFIG_SYSTEM_TRUSTED_KEYS = ""/CONFIG_SYSTEM_TRUSTED_KEYS=""/' .config
          make deb-pkg -j2 BUILD_TOOLS=y
          cd ..
          ls -l
          mkdir deb_archive
          mv  *.deb deb_archive/
          tar -czvf kernel_deb_files.tar.gz deb_archive/

          


      - name: Archive .deb files
        uses: actions/upload-artifact@v2
        with:
          name: kernel-deb-files
          path: kernel_deb_files.tar.gz
